# Generated by Django 6.0.1 on 2026-02-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfil_activo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_cedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('licencia_conducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefono_convencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_domiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('titulo_profesional', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('mostrar_perfil', models.BooleanField(default=True)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_formacion', models.BooleanField(default=True)),
                ('mostrar_referencias', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_venta_garage', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('total_horas', models.IntegerField(blank=True, null=True)),
                ('descripcion_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_patrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('email_empresa_patrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='cursos/')),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Curso Realizado',
                'verbose_name_plural': 'Cursos Realizados',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_desempenado', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('lugar_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('email_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_web_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto_empresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_empresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_inicio_gestion', models.DateField(blank=True, null=True)),
                ('fecha_fin_gestion', models.DateField(blank=True, null=True)),
                ('descripcion_funciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio_gestion', 'nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Formación Académica',
                'verbose_name_plural': 'Formaciones Académicas',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': 'Productos Académicos',
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_producto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Producto Laboral',
                'verbose_name_plural': 'Productos Laborales',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fecha_reconocimiento', models.DateField(blank=True, null=True)),
                ('descripcion_reconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_patrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto_auspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto_auspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruta_certificado', models.FileField(blank=True, null=True, upload_to='reconocimientos/')),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Referencia Personal',
                'verbose_name_plural': 'Referencias Personales',
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('estado_producto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_del_bien', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='hoja_de_vida.datospersonales')),
            ],
            options={
                'verbose_name': 'Venta Garage',
                'verbose_name_plural': 'Ventas Garage',
            },
        ),
    ]
