# Generated by Django 6.0.1 on 2026-01-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
