# Generated by Django 6.0.1 on 2026-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0002_datospersonales_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
