# Generated by Django 6.0.1 on 2026-02-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_de_vida', '0003_datospersonales_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_formacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_perfil',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_referencias',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
